# Root Cloud Build Configuration
# Delegates to metadata-api build

substitutions:
  _SERVICE_NAME: nexus-ummid-api
  _REGION: us-central1
  _GCP_PROJECT: agentics-foundation25lon-1899
  _GEMINI_API_KEY: ''

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories describe metadata-api \
          --location=us-central1 \
          --project=${_GCP_PROJECT} 2>/dev/null || \
        gcloud artifacts repositories create metadata-api \
          --repository-format=docker \
          --location=us-central1 \
          --project=${_GCP_PROJECT} \
          --description="Nexus-UMMID Metadata API container images"

  # Ensure Cloud Run service account has Firestore access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'grant-firestore-access'
    waitFor: ['create-repo']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get project number
        PROJECT_NUM=$$(gcloud projects describe ${_GCP_PROJECT} --format='value(projectNumber)')

        # Grant Firestore access (using datastore.user role)
        gcloud projects add-iam-policy-binding ${_GCP_PROJECT} \
          --member="serviceAccount:$${PROJECT_NUM}-compute@developer.gserviceaccount.com" \
          --role="roles/datastore.user" \
          --condition=None 2>/dev/null || echo "Firestore permission may already exist"

        # Also grant Storage access for GCS bucket
        gcloud projects add-iam-policy-binding ${_GCP_PROJECT} \
          --member="serviceAccount:$${PROJECT_NUM}-compute@developer.gserviceaccount.com" \
          --role="roles/storage.objectViewer" \
          --condition=None 2>/dev/null || echo "Storage permission may already exist"

        # Grant Vertex AI access for embeddings
        gcloud projects add-iam-policy-binding ${_GCP_PROJECT} \
          --member="serviceAccount:$${PROJECT_NUM}-compute@developer.gserviceaccount.com" \
          --role="roles/aiplatform.user" \
          --condition=None 2>/dev/null || echo "Vertex AI permission may already exist"

  # Build and deploy metadata-api
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    waitFor: ['grant-firestore-access']
    dir: 'apps/metadata-api'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${_GCP_PROJECT}/metadata-api/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/${_GCP_PROJECT}/metadata-api/${_SERVICE_NAME}:latest'
      - '.'
    timeout: '600s'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${_GCP_PROJECT}/metadata-api/${_SERVICE_NAME}'
    waitFor: ['build-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=us-central1-docker.pkg.dev/${_GCP_PROJECT}/metadata-api/${_SERVICE_NAME}:$SHORT_SHA'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=100'
      - '--timeout=300s'
      - '--concurrency=80'
      - '--port=8080'
      - '--set-env-vars=NODE_ENV=production,GCP_PROJECT=${_GCP_PROJECT},GEMINI_API_KEY=${_GEMINI_API_KEY}'
    waitFor: ['push-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sleep 10
        SVC_URL=$$(gcloud run services describe ${_SERVICE_NAME} --platform=managed --region=${_REGION} --format='value(status.url)')
        echo "Service URL: $$SVC_URL"
        curl -sf "$$SVC_URL/health" && echo "Health check passed" || echo "Health check failed"
    waitFor: ['deploy-api']

images:
  - 'us-central1-docker.pkg.dev/${_GCP_PROJECT}/metadata-api/${_SERVICE_NAME}:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/${_GCP_PROJECT}/metadata-api/${_SERVICE_NAME}:latest'

timeout: '1200s'
